---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: Enabling modules
  lineinfile:
    dest: /etc/modules
    line: "{{ item.line }}"
  with_items:
    - { line: 'ip_vs' }
    - { line: 'ip_vs_rr' }
    - { line: 'ip_vs_wrr' }
    - { line: 'ip_vs_sh' }

- name: Set timezone to UTC
  timezone:
    name: UTC
  register: timezone

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: python-apt dependency
  shell: apt-get install -y python-apt
  args:
    warn: no

# - name: apt-get upgrade
#   apt:
#     upgrade: full

- name: Reboot (my shell version)
  shell: sleep 2 && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True
  become: True

# - name: Reboot (as needed)
#   reboot:
#     reboot_timeout: 3600
#   when: cmdline or timezone or hostname is changed
#   tags:
#     - boot
#     - shutdown
# - name: Reboot Message
#   debug:
#     msg: "A reboot is required but the reboot module is a little wonky. Hopefully someone fixes this soon."
#   when: cmdline or timezone or hostname is changed

- name: Wait for Reboot
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    delay: 15
    search_regex: OpenSSH
  vars:
    ansible_connection: local
  become: False
  tags:
    - wait